//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkMe_WepApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E_Orders()
        {
            this.E_Invoces = new HashSet<E_Invoces>();
            this.E_Tasks = new HashSet<E_Tasks>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> FinishDateTime { get; set; }
        public int OrderStatusID { get; set; }
    
        public virtual E_Customers E_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_Invoces> E_Invoces { get; set; }
        public virtual LT_OrderStatuses LT_OrderStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_Tasks> E_Tasks { get; set; }
    }
}
