//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkMe_WepApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ParkingStations
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> ParkingLat { get; set; }
        public Nullable<double> PrkingLong { get; set; }
        public Nullable<int> MaxPlaces { get; set; }
        public Nullable<int> PriceFirstHour { get; set; }
        public Nullable<int> PriceAdditionalHour { get; set; }
        public Nullable<int> PricePerDay { get; set; }
        public Nullable<System.TimeSpan> WorkStartTime { get; set; }
        public Nullable<System.TimeSpan> WorkEndTime { get; set; }
    }
}
