//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkMe_WepApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_ValetsViolations
    {
        public int ValetID { get; set; }
        public int ViolationID { get; set; }
        public System.DateTime ViolationDate { get; set; }
        public string Remark { get; set; }
    
        public virtual E_Valets E_Valets { get; set; }
        public virtual LT_Violations LT_Violations { get; set; }
    }
}
